### ISSUE TITLE
Create Form

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#1]
## Value statement ##

As a **user** 
I want to **write down my aspired habits & assign a color** 
so **the visualization is more simple**

## Description ##
<img width="319" alt="Bildschirmfoto 2020-08-29 um 19 46 56" src="https://user-images.githubusercontent.com/67919897/91643082-7fb32c80-ea30-11ea-93aa-7fde114fd4a4.png">

## Acceptance criteria ##

- [x] Input fields available
- [x] Color for a category/habit can be chosen to differentiate 
- [ ] Input can be saved
- [x] Habit can only be created when mandatory fields are filled out
- [ ] Habits need to be saved locally

## Task ##

- [x] Add a 'Create' page
- [x] Create a form component
- [x] Add a form with:

- [x] Name of habit
- [x] Assigned color
- [ ] Add new habit in localStorage
- [x] Add requirements in the form
- [x] Create a save button
- [ ] Create a cancel button
- [x] Find colors for the user to choose from
- [ ] Write logic for which the current date is shown 

## Complexity ##

medium
