### ISSUE TITLE
Add localStorage

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#10]
## Value statement ##
As a **user**
I need to **be able to save my habits**
so **I can retrieve and check them every day** 

## Description ##
<img width="341" alt="Bildschirmfoto 2020-08-29 um 19 42 40" src="https://user-images.githubusercontent.com/67919897/91642990-d3714600-ea2f-11ea-9a25-9f6bb1beccae.png">

## Acceptance criteria ##

- [x] Checkboxes in habits can be saved and retrieved
- [x] Habits/Categories can be saved
- [x] Habits/Categories can be retrieved every time user opens the app

## Task ##

- [x] Set up localStorage
- [x] Save added habits/categories automatically on add
- [x] Retrieve saved habits/categories in the dashboard, with their dates matching

## Complexity ##
small
