### ISSUE TITLE
Add Navigation

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#14]
## Value statement ## 
As a **user**
I need **a navigation**
so **I can switch between the contents that are available**

## Description ##
<img width="431" alt="Bildschirmfoto 2020-09-08 um 11 19 37" src="https://user-images.githubusercontent.com/67919897/92458089-482d4880-f1c5-11ea-9577-6de5e8cbbcec.png">

## Acceptance criteria ##
- [x] Static Navigation on the bottom of the page
- [x] Navigation must be shown on all pages
- [x] 3 Buttons available 
- [x] Buttons switch to the according pages on click

## Task ##

- [x] Create Navigation component
- [x] Find svgs for buttons
- [x] Install React Router Dom
- [x] Unit Test
- [x] Write Story
**(Create pages later)**

## Complexity ##
small
