### ISSUE TITLE
Create monthly overview

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#3]
## Value statement ##
As a **user** I want to **see an overview of my completed habits of the month** so **I can see where I can improve**

## Description ##

<img width="316" alt="Bildschirmfoto 2020-08-29 um 19 49 17" src="https://user-images.githubusercontent.com/67919897/91643118-c4d75e80-ea30-11ea-886c-58629e3a6dc4.png">

## Acceptance criteria ## 

- [x] Monthly calendar of the current month is shown
- [x] Previous months are shown 
- Dots are added once user completes a habit for the day (In localStorage story)

## Tasks ##

- [x] Create calendar
- [x] Write logic for which the calendar updates itself daily/monthly/yearly (e.g. the correct month is shown, current day is marked) 
- Write logic that pushes the completed habit as a dot in calendar (In localStorage story)

## Complexity ##

medium
