### ISSUE TITLE
Add Form for Habits

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#6]
## Value statement ##
As a **user** 
I need to **have a form** 
so **I can write down and add my aspired habits to a list**

## Description ##
<img width="157" alt="Bildschirmfoto 2020-08-29 um 18 11 08" src="https://user-images.githubusercontent.com/67919897/91641269-7d96a100-ea23-11ea-91aa-5e6c9d6ba542.png">

## Acceptance criteria ## 

- [x] Form to add habits works
- [x] Each added habit needs to have a working checkbox
- [x] Added habits need to be displayed below the form
- [x] _When reloading the page, the previously added habits need to be displayed_ (not relevant for this story)
- [x] These features need to be shown in the home page

## Tasks ##

- [x] _Create Dashboard page_
- [x] Create Habit.js
- [x] Create Form.js
- [x] Create List.js

## Complexity ##

small
