### ISSUE TITLE
Create 'Tips 💡' page

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#7]
## Value statement ##
As a **user** 
I want to **receive tips on what habits to work on** 
so **I can add more or specify my aspired habits**

## Description ##

<img width="469" alt="Bildschirmfoto 2020-08-29 um 18 37 54" src="https://user-images.githubusercontent.com/67919897/91641730-ca2fab80-ea26-11ea-861b-0fe087a6808e.png">

## Acceptance criteria ##
- [ ] Tip page works
- [ ] Content for daily tips need to be compiled
- [ ] The page will add 1 tip per day
- [ ] The page will show all gathered tips over time at the first glance
- [ ] Each tip can be deleted

## Tasks ##
- [ ] Gather content for the tips page
- [ ] Create new 'Tip' component
- [ ] Tip page needs to show all previously loaded tips
- [ ] write delete-tip logic
- [ ] Write logic for daily update

## Complexity ## 
high
