### ISSUE TITLE
Add current date logic

### ISSUE THREAD

**Issue by denizulku** [denizulku/capstone-project#9]
## Value statement ##

As a **user**
I need to **have a calendar function**
so **I can check my completed and pending habits every day**

## Description ##
<img width="155" alt="Bildschirmfoto 2020-08-29 um 18 49 02" src="https://user-images.githubusercontent.com/67919897/91642557-93f52a80-ea2c-11ea-9b93-65354cab8d1b.png">
 
## Acceptance criteria ##

- [x] The home page needs to show the current date
- [x] Home page needs to update itself automatically each day with the current date 
- [ ] entries of a specific day need to match their dates (Connected to userstory #10 )

## Tasks ##

- [x] Add current date logic
- [ ] Match current date to current habit component (Connected to userstory #10 )

## Complexity ##
medium

**Comment by manuelpapa** [comment]
Super well-structured and easy readable board. Maybe you can think of creating some specified tags, e.g. `userstory`, `setup`, `API`, etc. to find your tasks even faster.
